Add sonar.scanner.force-deprecated-java-version that might fix
ERROR: Error during SonarScanner execution
At line:1 char:47
+ ... T_NUMBER) { & dotnet sonarscanner end /d:sonar.login="$env:SONAR_TOKE ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Error du...anner execution:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

ERROR:
The version of Java (1.8.0_221) you have used to run this analysis is deprecated and we will stop accepting it soon.
To make sure everyone is aware of this limitation we fail the analysis of new projects.
You can force the analysis with Java (1.8.0_221) temporarily by setting the property 'sonar.scanner.force-deprecated-java-version' to 'true'.
You can find more information here: https://sonarcloud.io/documentation/upcoming/
ERROR:
INFO: Final Memory: 29M/197M